name: Reflejo a Repositorio de Desarrollo

on:
  push:
    branches:
      - master

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: master
          
      - name: Configure Git
        run: |
          git config --global user.name "SIASIS Hacia Desarrollo Sync Bot"
          git config --global user.email "siasis-sync-from-GeoCoderDev@asuncion8.edu.pe"
      
      - name: Push to Repository 1
        run: |
          echo "Configurando repositorio de destino..."
          mkdir -p temp-external-repo
          cd temp-external-repo
          git clone https://x-access-token:${{ secrets.SIASIS_API02_INS1_REPOSITORIO_DESARROLLO_PAT }}@github.com/SIASIS-API02-DEV/API02.git .
          
          echo "Limpiando repositorio destino (excepto .git)..."
          find . -mindepth 1 -maxdepth 1 -not -path "./.git" -exec rm -rf {} \;
          
          echo "Copiando contenido actual sobre el repositorio destino..."
          find .. -mindepth 1 -maxdepth 1 -not -path "../.git" -not -path "../temp-external-repo" -exec cp -r {} . \;
          
          echo "Verificando cambios en repositorio destino..."
          git status
          
          echo "Añadiendo todos los cambios..."
          git add -A
          
          echo "Creando commit con los cambios..."
          # Solo hacer commit si hay cambios
          if git diff --staged --quiet; then
            echo "No hay cambios para sincronizar"
          else
            git commit -m "Sync changes from master branch (includes deleted files) $(date +'%Y-%m-%d %H:%M:%S')"
            echo "Haciendo push de los cambios al repositorio destino..."
            git push origin master
          fi
          
          cd ..
        continue-on-error: true

        
      # Repositorio 2
      - name: Push to Repository 2
        run: |
          echo "Configurando repositorio de destino 2..."
          mkdir -p temp-repo2
          cd temp-repo2
          git clone https://x-access-token:${{ secrets.SIASIS_API02_INS23_REPOSITORIO_DESARROLLO_PAT }}@github.com/SIASIS-API02-DEV-INS2/API02.git .

          echo "Limpiando repositorio destino 2 (excepto .git)..."
          find . -mindepth 1 -maxdepth 1 -not -path "./.git" -exec rm -rf {} \;

          echo "Copiando contenido actual sobre el repositorio destino 2..."
          find .. -mindepth 1 -maxdepth 1 -not -path "../.git" -not -path "../temp-repo1" -not -path "../temp-repo2" -not -path "../temp-repo3" -exec cp -r {} . \;

          echo "Verificando cambios en repositorio 2..."
          git status

          echo "Añadiendo todos los cambios..."
          git add -A

          echo "Creando commit con los cambios..."
          if git diff --staged --quiet; then
            echo "No hay cambios para sincronizar en repositorio 2"
          else
            git commit -m "Sync changes from master branch (includes deleted files)"
            echo "Haciendo push de los cambios al repositorio destino 2..."
            git push origin master
          fi

          cd ..
        continue-on-error: true